name: Formatting Check
run-name: Checking formatting through Black and Prettier
on: [ push ]
jobs:
  CheckBackend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pipenv
        run: pip install pipenv
      - name: Perform Checks
        run: |
          pipenv install --dev
          pipenv run black --check simpleBlog blog
      - run: echo "${{ job.status }}."
  CheckFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform Checks
        run: |
          yarn install
          yarn prettier_check
        working-directory: frontend
      - run: echo "${{ job.status }}."
